### ISSUE TITLE
Support AtomsBase.jl

### ISSUE THREAD

**Issue by rkurchin** [MineralsCloud/Express.jl#216]
I'm one of the developers of [AtomsBase](https://github.com/JuliaMolSim/AtomsBase.jl). I'm SO excited that Express.jl exists, and I'd love to discuss the best way that it could support the AtomsBase interface to further enhance interoperability amongst materials science packages in Julia!

I'd love to set up some time to discuss this, perhaps with some of the other AtomsBase team such as @mfherbst and @jgreener64 – maybe during JuliaCon?

**Comment by singularitti** [comment]
Cool @rkurchin! Sorry, I just saw your comment!

**Comment by rkurchin** [comment]
Glad you think it's cool! I'd be happy to set up a Zoom meeting or something to discuss if it would be helpful. Currently traveling but will be back with a more stable schedule starting the week of 6/13. What time zone are you in?

**Comment by singularitti** [comment]
@rkurchin Hi Rachel, I am glad to talk with you on Zoom. May I write emails to you?
